# Generated by Django 4.2.7 on 2023-11-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdsApi', '0002_requestcount_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ads_location_model',
            new_name='AdsLocationModel',
        ),
        migrations.RenameModel(
            old_name='Ads_Moel',
            new_name='AdsModel',
        ),
    ]
